language: go
cache:
  directories:
    - ${GOPATH}/src/github.com
    - ${GOPATH}/src/golang.org
go: 1.6
sudo: false

env:
    CI_SERVICE=travis-ci

before_install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/h12w/gosweep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/goimports

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - go test -v ./...

after_success:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh

